services:
  - type: web
    name: emotion-ai
    env: python
    rootDir: python_service
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13